from django.contrib import admin
from .models import Post, Comment

# Register your models here.
# When you register a model in the Django administration site,
# you get a user-friendly interface generated by introspecting your models that allows
# you to list, edit, create, and delete objects in a simple way.
# admin.site.register(Post)


@admin.register(Post)  # performs the same function as the admin.site.register()
class PostAdmin(admin.ModelAdmin):
    list_display = ('title', 'slug', 'author', 'publish', 'status')
    list_filter = ('status', 'created', 'publish', 'author')
    search_fields = ('title', 'body')
    prepopulated_fields = {'slug': ('title',)}
    raw_id_fields = ('author',)
    date_hierarchy = 'publish'
    ordering = ('status', 'publish')

# The list_display attribute allows you to set the fields of your model that you
# want to display on the administration object list page.


@admin.register(Comment)
class CommentAdmin(admin.ModelAdmin):
    list_display = ('name', 'email', 'post', 'created', 'active')
    list_filter = ('active', 'created', 'updated')
    search_fields = ('name', 'email', 'body')

